### ISSUE TITLE
How to obtain all info

### ISSUE THREAD

**Issue by xylone** [Hunv/can2mqtt#4] opened 2022-09-05 17:35 UTC
Hi!

Let me first start with saying that you did a great job!
Really impressive and very well documented and great tutorial.

I all got it working like a charm using the USBtin and a pi!
But... I'm not getting al the info:
<img width="371" alt="Schermafbeelding 2022-09-05 om 19 30 30" src="https://user-images.githubusercontent.com/2749350/188495997-206af690-d476-40d0-a4d2-643a14e2d126.png">

I tried to 'send' topics with the MQTT Explorer, but that didn't do anything.

I do have a different system: WPF 07 Cool
So I guess some of the ID's are different.

My question is, how did you determine the ID's.
Can you get me started, so I can change the JSON file to match my ID's?

Thanks in advance!

**Comment by Hunv** [comment] 2022-09-05 20:22
Hi Justin,
the LWZ (and I think also the WPF) is not sending all infos automatically. Most infos must be requested.
You have two options to do this.

Just yesterday I created a new release, that adds the /read suffix to the MQTT topic to send a trigger to the CAN bus to write the value to the bus.
i.e. heating/room/hc1/temperature/day/read will request the current value from the bus.

Alternatively, that is what I did, you can utilize the Linux cronjobs. Run "sudo crontab -e" on the Pi. I chose nano as editor. 
Paste the following line for each setting you want to request. Replace especially the four characters after the "FA" with the data you want to request. You can get the index value you need from the json. The example below will request the value every 5 minutes and expects that the can-utils are installed at the mentioned path.
`*/5 * * * * /opt/can-utils/cansend slcan0 6A2#3100FA05970000`

**Comment by xylone** [comment] 2022-09-06 14:41
Hi Hunv,

Thanks! That did the trick!
I do see some weird values, so I think some addresses or translations are different:
<img width="286" alt="Schermafbeelding 2022-09-06 om 16 39 29" src="https://user-images.githubusercontent.com/2749350/188664009-cc68cc03-a9e6-4bfd-8884-66f08da1d0b2.png">

I will start adding addresses, which I can check, to start with.
Then I will try to see a pattern of translation issues, so I can inform you too.

If you have any suggestions, let me know!

**Comment by xylone** [comment] 2022-09-07 09:39
If I want to know the Operational Status ->  /home/pi/can-utils/cansend slcan0 6A2#3100FA01760000
I get ??? 'returned'.  So it seems like the conversion is not correct. I tried to change the Conversion to al options I could find in the json file, but none of them returns a 'correct' value.

Can you point me in the right way how to determine the value/conversion?

**Comment by Hunv** [comment] 2022-09-07 10:38
Hi, the operational status should return the display of the heating in binary format.
See https://github.com/Hunv/can2mqtt/tree/master/infos/Stiebel%20Eltron%20LWZ%20504/OperatingStatus
Does this makes sense?

**Comment by Hunv** [comment] 2022-09-25 19:14
Hi @xylone ,
Does it makes sense that the value of that item is -1? Some values are working like this. Maybe there is an issue with this, but I like to know first if this is a possible case.

**Comment by xylone** [comment] 2022-09-26 09:16
A lot do probably, but not all.
Also the operationsswitch and operationstand are still the same value, while it should change a couple of times a day...

**Comment by Xtremdiver** [comment] 2022-10-27 22:49
Hi Hunv,

I took the opportunity today and upgraded from 3.2 to the new 4.1.
I was able to correct a few small errors in the installation description and incorporate them into my notes.

I, too, salute you for your great work - you've really made a a great leap forward.

As you mentioned here, there is a new feature - the /read.
It doesn't seem to work for me - why?!?
As an example, I would like to read or request the daily consumption of electricity and then read it out.
with the MQTT topic my/lwz504/meter/heating/power/day/KWh/read and my/lwz504/meter/heating/power/day/Wh/read each with an empty message, I don't get an update.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/5x93mn2/mqtt-pub.png" alt="mqtt-pub" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/RCpVGvg/mqtt-tree.png" alt="mqtt-tree" border="0"></a>

Thank you for your great work.
Many greetings
Xtremdiver

**Comment by Hunv** [comment] 2022-10-30 16:43
Hi @Xtremdiver ,
does this work for other topics?
Have you enabled the MqttAcceptSet-setting in the config? By default it is set to "false", so NOTHING will be written to the CANBus by can2mqtt. Also no read-messages.

**Comment by Xtremdiver** [comment] 2022-11-08 09:48
Hi Hunv,

I tried different approaches, unfortunately none of them worked.
I'll explain what I did. Since a CAN server is now running and this can be called up in the local network, I wrote a small script in Python* ( *I found it on the web ;o) ).


```
import can

bus = can.interface.Bus(bustype='socketcand', host="MYIPADDRESSofCANSERVER", port=29536, channel="slcan0")

# loop until Ctrl-C
try:
  while True:
    msg = bus.recv()
    print (msg)
except KeyboardInterrupt:
  pass
```


Now you can read along with all the news that goes back and forth.
Here is an excerpt as a small example. (Have messages written down and scrolled through the info menu on the heat pump)
```
...
Timestamp: 1667896812.272302 ID: 000006a1 X Rx DL: 7 31 00 fa 09 1c 00 00
Timestamp: 1667896812.283794 ID: 000006a1 X Rx DL: 7 31 00 fa 09 1d 00 00
Timestamp: 1667896812.290170 ID: 00000180 X Rx DL: 7 d2 21 fa 09 1c 00 d8 -> = 216 kWh
Timestamp: 1667896812.295295 ID: 00000180 X Rx DL: 7 d2 21 fa 09 1d 00 01 -> =   1 MWh
...
```

started the command on the Raspberry Pi via SSH
`/opt/can-utils/cansend slcan0 6A1#3100FA091C0000`
worked

started the command on the Raspberry Pi via SSH
`/opt/can-utils/cansend slcan0 6A1#3100FA091D0000`
worked

via MQTT:
`my/lwz504/meter/dwh/power/total/KWh/read`
or
`my/lwz504/meter/dwh/power/total/MWh/read`
didn't bring any result!

In your list is the "Receiver": "6A0".
`/opt/can-utils/cansend slcan0 6A0#3100FA091C0000`
`/opt/can-utils/cansend slcan0 6A0#3100FA091D0000`
These were also successful

It is therefore not possible for me to trigger a read with /read via the MQTT-tree.

Here the configurations:

<a href="https://ibb.co/2cVnPJ9"><img src="https://i.ibb.co/nQdgfpG/2022-11-08-Auszug-JSON-Datei.png" alt="2022-11-08-Auszug-JSON-Datei" border="0"></a></br>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/j3KPWc6/2022-11-08-can2mqtt-config-file.png" alt="2022-11-08-can2mqtt-config-file" border="0"></a>

Why does "StiebelEltron.json" actually say under ReadOnly: false? it doesn't make any sense to overwrite them.

**Comment by Hunv** [comment] 2022-11-10 08:29
Hi,
your config looks good. I guess you restarted can2mqtt after changing the config.
The ReadOnly:false doesn't make sense at that point, that is true. I am not sure anymore, If I got this information from somewhere. Maybe it is possible to overwrite the value. So it doesn't make sense to do so, but technically it may be possible - or it is just an error in the config.
The name is just to know what the values are for. In most cases it is, what is shown at the display of the LWZ. In some cases the same values are at multiple places on the LWZ menu and have different names. In that case, it is the first name I found.

The CanSenderID is the CAN-ID can2mqtt uses to send CAN messages. This are the first 3 characters of the CAN frame. See here https://github.com/Hunv/can2mqtt/blob/master/infos/can_telegram.txt.
So the first three characters of CAN messages can2mqtt sends, will be the CanSenderId.

**Comment by Mortinke** [comment] 2022-11-21 19:13
Firstly, @Hunv thank you for the great project and your work.

I also had issues with the `/read` requests and the can2mqtt log helped me a lot.

To enable the can2mqtt log I changed the lines `StandardOutput` and `StandardError` in the service configuration `/etc/systemd/system/can2mqtt.service`
```
- StandardOutput=inherit
- StandardError=inherit
+ StandardOutput=append:<path-to-your-logfile>/<logfile-name>
+ StandardError=append:<path-to-your-logfile>/<error-logfile-name>
```

For instance, with `"NoUnits": true,` in the configuration I always got this exception:
```
Received MQTT READ Message; Topic = heating/room/hc1/temperature/day/read and Payload =
Already connected to SocketCanD.
Failed to send a read via CAN bus. Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at can2mqtt.Translator.StiebelEltron.StiebelEltron.TranslateBack(String topic, String value, String senderId, Boolean noUnit, String canOperation) in D:\Productions\#git\can2mqtt\can2mqtt_core\can2mqtt_core\translator\stiebel_eltron\StiebelEltron.cs:line 122
   at can2mqtt.Can2Mqtt.ReadCan(String topic, String canServer, Int32 canPort) in D:\Productions\#git\can2mqtt\can2mqtt_core\can2mqtt_core\can2mqtt.cs:line 266
```

After I changed to `"NoUnits": true` everything work as expected. In the log file you can always see whether the request arrived and was processed at all. You should see something like this:
```
Received MQTT READ Message; Topic = heating/room/hc1/temperature/day/read and Payload = foobar
Already connected to SocketCanD.
CAN Frame is: 6A0#6101FA00050000
Sending CAN Frame: < send 6A0 7 61 1 FA 0 5 0 0 >
Sending CAN Verify Frame: < send 6A0 7 61 1 FA 0 5 0 0 >
```

I don't know why a payload is mandatory even though it is not used. If you use an empty message, you will see the following log message and nothing will be executed, see also [here](https://github.com/Hunv/can2mqtt/blob/1dfc84c01d0164421448f21f3e72337e5bac3573/can2mqtt_core/can2mqtt_core/can2mqtt.cs#L172)
```
Received MQTT READ Message; Topic = heating/room/hc1/temperature/day/read WITH NO PAYLOAD
```

**Comment by Mortinke** [comment] 2022-11-23 19:20
OMG, my bad, sorry for the confusion :(
The first time I meant  `"NoUnits": false`
==> with `"NoUnits": false` I got the exception. After I changed the configuration to `"NoUnits": true` everything worked.

I updated my comment so others will not be confused too.

**Comment by Hunv** [comment] 2022-12-01 06:36
@Mortinke : Did you already tested the new release? I am curious if this fixed it as I cannot reproduce the problem.

**Comment by Hunv** [comment] 2023-12-26 14:06
No further response. Closing issue.

**Closed by Hunv** 2023-12-26 14:06 UTC
Labels: help wanted
