### ISSUE TITLE
client tried to access unauthorized bus.

### ISSUE THREAD

**Issue by oduzus** [Hunv/can2mqtt#14] opened 2022-12-22 12:27 UTC
Hi,

i really like this project as well. I have tested it already in version 2 and 3.1.
In Version 3.1 I got it to a point where is sends mqtt topics to the broker, but unfortunately just once and then it stopped sending updates. Now 1 year later i thought let's give i a new try and found the latest version changed to socketcan.
I have installed it on a new rasperry os setup.
I am using a canHAT on my Pi 4 so no slcan tty can be bind. My can0 is running and candump shows me the traffic of my THZ304.

the setting for the can interface i did like this:

```
sudo ip link set can0 type can bitrate 20000
sudo ifconfig can0 up
```

now i came to a stop when can2mqtt wants to opening the interface:

can2mqtt messages:
```
CONNECTED TO SOCKETCAND 192.168.77.59 ON PORT 29536
Handshake successful. Opening CAN interface...
Disconnected from canServer 192.168.77.59 Port 29536
```

socketcan messages:
```
Using network interface 'eth0'
Listen adress is 192.168.77.59
Broadcast adress is 192.168.77.255
creating broadcast thread...
binding socket to 192.168.77.59:29536
client connected
client tried to access unauthorized bus.
Closing client connection.
```
Any thoughts how I can get it up and running

**Comment by Hunv** [comment] 2022-12-22 13:36
Hi, do you have authentication enabled on your broker?

**Comment by oduzus** [comment] 2022-12-22 14:19
Hi,
do you mean on the mqtt Broker?
No, it allows anonymous clients for now.

I think the socketcand closes the connection if the can2mqtt.dll tries to establish the raw profile on the can.

**Comment by Hunv** [comment] 2023-03-23 21:07
Hi @oduzus, I checked if I can find something about this, but actually I cannot repoduce it.
I checked the sourcecode of socketcand (here, line 512: https://github.com/linux-can/socketcand/blob/master/socketcand.c) and it checked for a variable called "found". If this is 0, it returns that error.
Regarding the three log lines the connection to socketcand was successfully established (a "< hi >" was sent successfully).
And after that it fails. The next command to socketcand is "< open slcan0 >". And here is the issue :) Your adapter has a different name.
I added a new setting to the config.json where you can define the name of the CanInterfaceName.
The issue is fixed in the sourcecode and will be fixed at the next release.

**Closed by Hunv** 2023-03-23 21:07 UTC

**Comment by Oldscrewdriver** [comment] 2024-02-02 18:40
Hi, somebody please can confirm this, I use the new config wit the option:

"CanInterfaceName":"can0",

but it not works, get also the error:

"... client tried to access unauthorized bus.
Closing client connection."

**Comment by oduzus** [comment] 2024-02-02 19:23
Hi Oldscrewdriver,
basically this works with my CAN Hardware. I have my can Interface also set with name "can0".
I have running a start script which is initialising the interface after reboot.
start script:

```
sudo ip link set can0 type can bitrate 20000
sudo ifconfig can0 up
```
try `ifconfig can0` and you should see if the interface is running `can0: flags=193<UP,RUNNING,NOARP>  mtu 16`

I hope this helps
